export const pulseLabels = {
  fr: {
    today: "Aujourd’hui",
    dueToday: "Tâches dues aujourd’hui",
    overdue: "Tâches en retard",
    closingThisWeek: "Closing cette semaine",
    noNextAction: "Sans prochaine action",
    staleDeals: "Sans activité depuis 14 jours",
    empty: "Aucun élément",
    retry: "Réessayer",
    assigned: "Mes éléments assignés",
    workspace: "Espace de travail",
    assignee: "Assigné à",
    priority: "Priorité",
    opportunity: "Opportunité",
    none: "Non assigné",
    nextAction: "Prochaine action",
    lastActivity: "Dernière activité",
    low: "Basse",
    medium: "Normale",
    high: "Haute",
    urgent: "Urgente",
    history: "Historique",
    configured: "Déjà enregistré · laisser vide pour conserver",
    complete: "Terminée",
  },
  en: {
    today: "Today",
    dueToday: "Tasks due today",
    overdue: "Overdue tasks",
    closingThisWeek: "Closing this week",
    noNextAction: "No next action",
    staleDeals: "No activity for 14 days",
    empty: "No items",
    retry: "Retry",
    assigned: "Assigned to me",
    workspace: "Workspace",
    assignee: "Assignee",
    priority: "Priority",
    opportunity: "Opportunity",
    none: "Unassigned",
    nextAction: "Next action",
    lastActivity: "Last activity",
    low: "Low",
    medium: "Normal",
    high: "High",
    urgent: "Urgent",
    history: "History",
    configured: "Already saved · leave blank to keep",
    complete: "Completed",
  },
  es: {
    today: "Hoy",
    dueToday: "Tareas para hoy",
    overdue: "Tareas vencidas",
    closingThisWeek: "Cierre esta semana",
    noNextAction: "Sin próxima acción",
    staleDeals: "Sin actividad en 14 días",
    empty: "Sin elementos",
    retry: "Reintentar",
    assigned: "Asignados a mí",
    workspace: "Espacio de trabajo",
    assignee: "Responsable",
    priority: "Prioridad",
    opportunity: "Oportunidad",
    none: "Sin asignar",
    nextAction: "Próxima acción",
    lastActivity: "Última actividad",
    low: "Baja",
    medium: "Normal",
    high: "Alta",
    urgent: "Urgente",
    history: "Historial",
    configured: "Guardado · dejar vacío para conservar",
    complete: "Completada",
  },
};
export function phase1Labels(language: string) {
  return pulseLabels[language as keyof typeof pulseLabels] || pulseLabels.en;
}
